# Change these first
owner: admonstrator # Your GitHub organization or username, where this repository lives
repo: glinet-uptime # The name of this repository

sites:
  - name: GL.iNet Website (Global)
    url: https://www.gl-inet.com
  - name: GL.iNet Forum (Global)
    url: https://forum.gl-inet.com
  - name: GL.iNet Forum (China)
    url: https://forum.gl-inet.cn

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: glinet-uptime.admon.in.ua
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: GL.iNet Status
  introTitle: "Is any GL.iNet service down?"
  introMessage: This status page shows the real-time status of GL.iNet services.
  navbar:
    - title: Status
      href: /
    - title: GL.iNet Forum
      href: https://forum.gl-inet.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
