# Change these first
owner: admonstrator # Your GitHub organization or username, where this repository lives
repo: glinet-uptime # The name of this repository

sites:
  - name: GL.iNet Website (Global)
    url: https://www.gl-inet.com
  - name: GL.iNet Forum (Global)
    url: https://forum.gl-inet.com
  - name: GL.iNet Forum (China)
    url: https://forum.glinet.cn

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: glinet-uptime.admon.in.ua
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
